services:
  todo-api:
    image: local/todo-app-api:latest # Use as the image name for the built image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

    # Ensure the container restarts unless explicitly stopped
    restart: unless-stopped
    container_name: todo_app_api_container