services:
  todo-api:
    # image: docker.ch.pbk:8085/my-todo-api:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

    # Ensure the container restarts unless explicitly stopped
    restart: unless-stopped
    container_name: todo_app_api_container